/**
 * build-data.js
 * 
 * Prepares all data for the frontend by:
 * 1. Copying curated JSON files from /data → /src/data
 * 2. Combining per-species GBIF files from /scripts/output/gbif → /src/data/distributions.json
 * 3. Generating a manifest of what's available
 * 
 * Run after fetch-gbif.js, or anytime you edit the curated data files.
 * 
 * Usage:
 *   node scripts/build-data.js           # full build
 *   node scripts/build-data.js --stats   # show stats without building
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ============================================
// PATHS
// ============================================

const PATHS = {
  // Source: curated data (you edit these)
  curatedDir: path.join(__dirname, '..', 'data'),
  
  // Source: GBIF fetch output (generated by fetch-gbif.js)
  gbifDir: path.join(__dirname, 'output', 'gbif'),
  
  // Destination: frontend data folder (React imports from here)
  frontendDir: path.join(__dirname, '..', 'src', 'data')
};

const CURATED_FILES = ['species.json', 'relationships.json', 'cascades.json', 'species-images.json'];

// ============================================
// HELPERS
// ============================================

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function fileSize(filePath) {
  const bytes = fs.statSync(filePath).size;
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function formatNum(n) {
  return n.toLocaleString();
}

// ============================================
// STEP 1: COPY CURATED DATA
// ============================================

function copyCuratedData() {
  console.log('\n─── Step 1: Copy curated data ───\n');

  let copied = 0;

  for (const file of CURATED_FILES) {
    const src = path.join(PATHS.curatedDir, file);
    const dest = path.join(PATHS.frontendDir, file);

    if (!fs.existsSync(src)) {
      console.log(`  ⚠ Missing: ${file} (not found in /data)`);
      continue;
    }

    fs.copyFileSync(src, dest);
    console.log(`  ✓ ${file} → src/data/${file} (${fileSize(src)})`);
    copied++;
  }

  console.log(`\n  Copied ${copied}/${CURATED_FILES.length} curated files`);
  return copied;
}

// ============================================
// STEP 2: BUILD DISTRIBUTIONS
// ============================================

function buildDistributions() {
  console.log('\n─── Step 2: Build distributions.json ───\n');

  if (!fs.existsSync(PATHS.gbifDir)) {
    console.log('  ⚠ No GBIF data found at scripts/output/gbif/');
    console.log('  Run fetch-gbif.js first to download occurrence data.');
    console.log('  Skipping distributions build.\n');
    return null;
  }

  const gbifFiles = fs.readdirSync(PATHS.gbifDir)
    .filter(f => f.endsWith('.json') && !f.startsWith('_'));

  if (gbifFiles.length === 0) {
    console.log('  ⚠ No species files found in scripts/output/gbif/');
    console.log('  Skipping distributions build.\n');
    return null;
  }

  // Load species.json to get the canonical species list
  const speciesPath = path.join(PATHS.curatedDir, 'species.json');
  const speciesData = JSON.parse(fs.readFileSync(speciesPath, 'utf8'));
  const speciesIds = new Set(speciesData.species.map(s => s.id));

  const distributions = {};
  let totalPoints = 0;
  let speciesWithData = 0;
  let speciesWithoutData = 0;

  // Process each GBIF file
  for (const file of gbifFiles) {
    const filePath = path.join(PATHS.gbifDir, file);
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    const id = data.species.id;

    // Only include species that are in our curated list
    if (!speciesIds.has(id)) {
      console.log(`  ⊘ Skipping ${id} (not in species.json)`);
      continue;
    }

    const pointCount = data.points?.length || 0;

    distributions[id] = {
      points: data.points || [],
      summary: data.summary || {},
      metadata: {
        totalPoints: pointCount,
        dateRange: data.metadata?.dateRange || 'unknown',
        fetchedAt: data.metadata?.fetchedAt || 'unknown'
      }
    };

    totalPoints += pointCount;
    speciesWithData++;
    console.log(`  ✓ ${data.species.commonName.padEnd(28)} ${formatNum(pointCount)} points`);
  }

  // Check which species are missing GBIF data
  const fetched = new Set(Object.keys(distributions));
  for (const sp of speciesData.species) {
    if (!fetched.has(sp.id)) {
      distributions[sp.id] = {
        points: [],
        summary: {},
        metadata: { totalPoints: 0, dateRange: 'none', fetchedAt: 'none' }
      };
      speciesWithoutData++;
      console.log(`  ○ ${sp.commonName.padEnd(28)} no GBIF data (placeholder added)`);
    }
  }

  // Write combined file
  const outputPath = path.join(PATHS.frontendDir, 'distributions.json');
  const output = {
    metadata: {
      generatedAt: new Date().toISOString(),
      speciesCount: speciesWithData,
      totalPoints: totalPoints,
      pointFormat: '[latitude, longitude, year, month]'
    },
    species: distributions
  };

  fs.writeFileSync(outputPath, JSON.stringify(output));  // No pretty-print — keep it compact
  
  console.log(`\n  Species with data: ${speciesWithData}`);
  console.log(`  Species without data: ${speciesWithoutData}`);
  console.log(`  Total points: ${formatNum(totalPoints)}`);
  console.log(`  Output: src/data/distributions.json (${fileSize(outputPath)})`);

  return { speciesWithData, totalPoints };
}

// ============================================
// STEP 3: GENERATE MANIFEST
// ============================================

function generateManifest() {
  console.log('\n─── Step 3: Generate manifest ───\n');

  const manifest = {
    generatedAt: new Date().toISOString(),
    files: {}
  };

  const dataFiles = fs.readdirSync(PATHS.frontendDir)
    .filter(f => f.endsWith('.json'));

  for (const file of dataFiles) {
    const filePath = path.join(PATHS.frontendDir, file);
    const stats = fs.statSync(filePath);
    manifest.files[file] = {
      size: stats.size,
      sizeFormatted: fileSize(filePath),
      modified: stats.mtime.toISOString()
    };
    console.log(`  ${file.padEnd(30)} ${fileSize(filePath)}`);
  }

  const manifestPath = path.join(PATHS.frontendDir, '_manifest.json');
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
  console.log(`\n  Manifest saved to src/data/_manifest.json`);

  return manifest;
}

// ============================================
// STATS MODE
// ============================================

function showStats() {
  console.log('\n─── Data Stats ───\n');

  // Curated data
  console.log('Curated data (/data):');
  for (const file of CURATED_FILES) {
    const filePath = path.join(PATHS.curatedDir, file);
    if (fs.existsSync(filePath)) {
      const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
      if (file === 'species.json') {
        console.log(`  species.json: ${data.species.length} species`);
      } else if (file === 'relationships.json') {
        console.log(`  relationships.json: ${data.relationships.length} relationships`);
      } else if (file === 'cascades.json') {
        console.log(`  cascades.json: ${data.cascades.length} cascades`);
      }
    } else {
      console.log(`  ${file}: NOT FOUND`);
    }
  }

  // GBIF data
  console.log('\nGBIF data (scripts/output/gbif):');
  if (fs.existsSync(PATHS.gbifDir)) {
    const files = fs.readdirSync(PATHS.gbifDir).filter(f => f.endsWith('.json') && !f.startsWith('_'));
    let totalPoints = 0;
    for (const file of files) {
      const data = JSON.parse(fs.readFileSync(path.join(PATHS.gbifDir, file), 'utf8'));
      totalPoints += data.points?.length || 0;
    }
    console.log(`  ${files.length} species fetched, ${formatNum(totalPoints)} total points`);
  } else {
    console.log('  Not yet fetched (run fetch-gbif.js)');
  }

  // Frontend data
  console.log('\nFrontend data (src/data):');
  if (fs.existsSync(PATHS.frontendDir)) {
    const files = fs.readdirSync(PATHS.frontendDir).filter(f => f.endsWith('.json') && !f.startsWith('_'));
    for (const file of files) {
      console.log(`  ${file.padEnd(30)} ${fileSize(path.join(PATHS.frontendDir, file))}`);
    }
  } else {
    console.log('  Not yet built (run build-data.js)');
  }
}

// ============================================
// MAIN
// ============================================

function main() {
  const args = process.argv.slice(2);
  const statsOnly = args.includes('--stats');

  console.log('='.repeat(50));
  console.log('Build Data — UK Ecological Web');
  console.log('='.repeat(50));

  if (statsOnly) {
    showStats();
    return;
  }

  // Verify curated data exists
  if (!fs.existsSync(PATHS.curatedDir)) {
    console.error('\n✗ Curated data folder not found: /data');
    console.error('  Create it and add species.json, relationships.json, cascades.json');
    process.exit(1);
  }

  // Ensure frontend data dir exists
  ensureDir(PATHS.frontendDir);

  // Run build steps
  const curatedCount = copyCuratedData();
  const distResult = buildDistributions();
  const manifest = generateManifest();

  // Summary
  console.log('\n' + '='.repeat(50));
  console.log('BUILD COMPLETE');
  console.log('='.repeat(50));
  console.log(`\n  Curated files copied: ${curatedCount}`);
  if (distResult) {
    console.log(`  Distribution species: ${distResult.speciesWithData}`);
    console.log(`  Distribution points: ${formatNum(distResult.totalPoints)}`);
  } else {
    console.log('  Distributions: skipped (no GBIF data yet)');
  }
  console.log(`\n  Frontend data ready at: src/data/`);
  console.log(`\n  Next: run the dev server and start building components!`);
}

main();
